=== senateurritchie/chatbot/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >

	
<xsd:simpleType name="email">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[\w_\+-]+@[\w-]+\.[a-zA-Z]{2,}" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="phone">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(\+|00)\d{3}\d+" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:element name="Website" type="xsd:anyURI" />

	<xsd:element name="Name">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="3" />
				<xsd:maxLength value="30" />
				<xsd:whiteSpace value="collapse" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>


	<xsd:element name="Email">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="email">
					
					<xsd:attribute name="type">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="personal" />
								<xsd:enumeration value="profesional" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>

				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
		
	</xsd:element>

	<xsd:element name="Phone">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="phone">
					<xsd:attribute name="type">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="personal" />
								<xsd:enumeration value="profesional" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="Phones">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Phone" maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="Emails">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Email" maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="Address">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="Emails" />
				<xsd:element ref="Phones" />
				<xsd:element ref="Website" />
			</xsd:all>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="Author">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="Name" />
				<xsd:element ref="Address" />
			</xsd:all>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="Settings">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="Name" />
				<xsd:element ref="Website" minOccurs="0" />
				<xsd:element ref="Author" />
				<xsd:element name="Welcome" type="xsd:string" />

				<xsd:element name="Version">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:pattern value="\d+(\.\d+){2}" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>

			</xsd:all>
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="Label">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="is-prefixed" type="xsd:boolean" default="false" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="Labels">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Label" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="Question">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Labels" />
				<xsd:element ref="Responses" />
			</xsd:sequence>

			<xsd:attribute name="type" default="predefined">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="predefined" />
						<xsd:enumeration value="fallback" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="Response">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Labels" />
			</xsd:sequence>
			<!-- 
				Permet de savoir si cette reponse est utilisée comme prefixe au autres reponses 
			-->
			<xsd:attribute name="is-prefix" type="xsd:boolean" default="false" />
			<!-- 
				Permet de joindre une autre reponse à la reponse encours 
			-->
			<xsd:attribute name="join" type="xsd:IDREF" />
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="Responses">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Response" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	
	<xsd:element name="Questions">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Question" maxOccurs="unbounded" />
				<xsd:element name="Default" >
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="Responses" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="Unknows">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Labels" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="Chatbot">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Settings" />
				<xsd:element ref="Questions" />
				<xsd:element ref="Unknows" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== senateurritchie/chatbot/data.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Chatbot 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd" >

	<!-- LES PARAMETRES DU BOT -->
	<Settings>
		<Name>COA BOT</Name>
		<Birth>1980</Birth>
		<Company>
			<Name>Côte Ouest Audiovisuel</Name>
			<Birth>1980</Birth>
			<Ceo>Bernard Azria</Ceo>
		</Company>
		<Welcome>
			***************************************************************************
			*                                                                         *
			*           BIENVENU, COMMENT POUVONS-NOUS VOUS AIDER?                    *
			*                                                                         *
			***************************************************************************
		</Welcome>
		<Website>https://www.coteouest.tv</Website>
		<Version>1.0.0</Version>

		<Author>
			<Name>Zacharie A. Assagou</Name>
			<Address>
				<Emails>
					<Email type="personal">zakeszako@yahoo.fr</Email>
					<Email type="profesional">webmaster@coteouest.ci</Email>
				</Emails>

				<Phones>
					<Phone type="personal">+22571439414</Phone>
					<Phone type="profesional">+22522479613</Phone>
				</Phones>
				<Website>https://chatbot.io/about</Website>
			</Address>
		</Author>
	</Settings>
	
	<!-- LES QUESTIONS APPRISES -->
	<Questions>
		<Question>

			<Labels>
				<Label>Comment t'appelles-tu</Label>
				<Label>Comment tu t'appelles</Label>
				<Label>Comment vous appellez-vous</Label>
				<Label>Comment vous vous appellez</Label>
				
				<Label>Quel est {{ votre|ton }} nom</Label>
				<Label>{{ Votre|Ton }} nom</Label>
				<Label>Nom</Label>
			</Labels>

			<Responses>
				
				<Response>
					<Labels>
						<Label>{{ On|Je }} m'appelle __NAME__.</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>Tu peux m'appeller __NAME__.</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>Vous pouvez m'appeller __NAME__.</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>Mon nom est __NAME__.</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>Je m'appelle __NAME__ à l'Etat Civil.</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>__NAME__ à l'Etat Civil.</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>__NAME__ est mon nom.</Label>
					</Labels>
				</Response>

			</Responses>

		</Question>

		<Question>

			<Labels>
				<Label>Quel age as-tu</Label>
				<Label>Quel age avez-vous</Label>
				<Label>Quel est ton age</Label>
				<Label>ton age</Label>

				<Label>Quel es ta date de naissance</Label>
				<Label>Ta date de naissance</Label>
				<Label>Ton année de naissance</Label>
				<Label>Date de naissance</Label>
				
			</Labels>

			<Responses>

				<Proactivity>
					<Labels>
						<Label>je {{te|vous}} propose de parler de « __COMPANY_NAME__ »</Label>
						<Label>Et si {{vous|toi}} et moi parlions de « __COMPANY_NAME__ »</Label>
						<Label>Revenons à « __COMPANY_NAME__ » {{stp|svp}}.</Label>
						<Label>Parlons de « __COMPANY_NAME__ » {{stp|svp}}</Label>
					</Labels>
				</Proactivity>


				<Response>
					<Labels>
						<Label>je suis de __BIRTH__</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>je suis né en __BIRTH__</Label>
					</Labels>
				</Response>


				<Response>
					<Labels>
						<Label>je suis né vers __BIRTH__</Label>
					</Labels>
				</Response>

			</Responses>
		</Question>


		<Question>
			<Labels>
				<Label>en quel année a été {{fondé|crée}} l'entreprise</Label>
				<Label>en quel année a été {{fondé|crée}} __COMPANY_NAME__</Label>
				<Label>date de création de __COMPANY_NAME__</Label>
				<Label>date de création de l'entreprise</Label>
				<Label>naissance de l'entreprise</Label>
				<Label>l'entreprise</Label>
				<Label>__COMPANY_NAME__</Label>
			</Labels>

			<Responses>

				<Response>
					<Labels>
						<Label>__COMPANY_NAME__ {{a été crée|existe|opère}} depuis 1993</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>evidenment __COMPANY_NAME__ {{a été crée|existe|opère}} depuis 1993</Label>
					</Labels>
				</Response>

			</Responses>

		</Question>

		<Question>
			<Labels>
				<Label>qui dirige cette entreprise</Label>
				<Label>qui dirige __COMPANY_NAME__</Label>
				<Label>c'est qui le {{directeur|dg|pdg|ceo}}</Label>
				<Label>qui est le {{directeur|dg|pdg|ceo}} cette {{entreprise|boite}}</Label>
			</Labels>

			<Responses>

				<Response>
					<Labels>
						<Label>bien évidenment le CEO est __COMPANY_CEO__</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>Le CEO est __COMPANY_CEO__</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>Il {{se nomme|s'appelle}} __COMPANY_CEO__</Label>
					</Labels>
				</Response>
				
			</Responses>

		</Question>


		<Default>

			<Responses>
				
				<Response is-prefix="true">
					<Labels>
						<Label>Désolé, </Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>je ne comprends pas.</Label>
					</Labels>
				</Response>

				<Response>
					<Labels>
						<Label>pouvez-vous reformuler svp ?</Label>
					</Labels>
				</Response>

			</Responses>

		</Default>
	</Questions>
	
	<!-- LES QUESTIONS A APPRENDRE -->
	<Unknows>
		
	</Unknows>
</Chatbot>
